# Generated by Django 4.2.4 on 2023-08-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskTracker', '0002_customuser_is_active_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('manager', 'manager'), ('team leader', 'team leader'), ('team member', 'team member')], default='team member', max_length=15),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('Inprogress', 'In progress'), ('UnderReview', 'Under Review'), ('Done', 'Done')], default='Assigned', max_length=12),
        ),
    ]
